---
- name: CONFIGURE | Disable system bell
  community.general.dconf:
    key: "/org/gnome/desktop/wm/preferences/audible-bell"
    value: "{{ wm_preferences.audible_bell }}"
    state: "{{ 'present' if wm_preferences.audible_bell is defined else 'absent' }}"

