---
- name: CONFIGURE | Enable Night Light
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
    value: "{{ _settings_daemon_plugins_color.night_light_enabled | default(None) }}"
    state: "{{ 'present' if _settings_daemon_plugins_color.night_light_enabled is defined else 'absent' }}"
