---
- name: CONFIGURE | Disable location
  community.general.dconf:
    key: "/org/gnome/system/location/enabled"
    value: "{{ location_enabled }}"
    state: present
  when: location_enabled is defined

- name: CONFIGURE | Disable camera
  community.general.dconf:
    key: "/org/gnome/desktop/privacy/disable-camera"
    value: "{{ disable_camera }}"
    state: present
  when: disable_camera is defined

- name: CONFIGURE | Disable microphone
  community.general.dconf:
    key: "/org/gnome/desktop/privacy/disable-microphone"
    value: "{{ disable_microphone }}"
    state: present
  when: disable_microphone is defined

