---
- name: CONFIGURE | Disable location
  community.general.dconf:
    key: "/org/gnome/system/location/enabled"
    value: "{{ _system_location.enabled | default(None) }}"
    state: "{{ 'present' if _system_location.enabled is defined else 'absent' }}"

- name: CONFIGURE | Disable camera
  community.general.dconf:
    key: "/org/gnome/desktop/privacy/disable-camera"
    value: "{{ privacy.disable_camera | default(None) }}"
    state: "{{ 'present' if privacy.disable_camera is defined else 'absent' }}"

- name: CONFIGURE | Disable microphone
  community.general.dconf:
    key: "/org/gnome/desktop/privacy/disable-microphone"
    value: "{{ privacy.disable_microphone | default(None) }}"
    state: "{{ 'present' if privacy.disable_microphone is defined else 'absent' }}"

