---
- name: CONFIGURE | Disable hot-corners
  community.general.dconf:
    key: "/org/gnome/desktop/interface/enable-hot-corners"
    value: "{{ interface.enable_hot_corners | default(None) }}"
    state: "{{ 'present' if interface.enable_hot_corners is defined else 'absent' }}"

- name: CONFIGURE | Focus window via mouse
  community.general.dconf:
    key: "/org/gnome/desktop/wm/preferences/focus-mode"
    value: "{{ wm_preferences.focus_mode | default(None) }}"
    state: "{{ 'present' if wm_preferences.focus_mode is defined else 'absent' }}"

- name: CONFIGURE | Ensure mouse speed is configured when set
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/mouse/speed"
    value: "{{ peripherals_mouse.speed | default('0') }}"
    state: "{{ 'present' if peripherals_mouse.speed is defined else 'absent' }}"

