---
- name: CONFIGURE | Show weekdate in calendar
  community.general.dconf:
    key: "/org/gnome/desktop/calendar/show-weekdate"
    value: "{{ calendar.show_weekdate | default(None) }}"
    state: "{{ 'present' if calendar.show_weekdate is defined else 'absent' }}"

