---
- name: CONFIGURE | Change close window keybinding to Super+Shift+q
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/close"
    value: "{{ close }}"
    state: present
  when: close is defined

- name: CONFIGURE | Change toggle fullscreen keybinding to Super+f
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/toggle-fullscreen"
    value: "{{ toggle_fullscreen }}"
    state: present
  when: toggle_fullscreen is defined

- name: CONFIGURE | Change search keybinding to Super+d
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/search"
    value: "{{ search }}"
    state: present
  when: search is defined

