---
- name: CONFIGURE | Disable hot-corners
  community.general.dconf:
    key: "/org/gnome/desktop/interface/enable-hot-corners"
    value: "{{ enable_hot_corners }}"
    state: present
  when: enable_hot_corners is defined

- name: CONFIGURE | Focus window via mouse
  community.general.dconf:
    key: "/org/gnome/desktop/wm/preferences/focus-mode"
    value: "{{ focus_mode }}"
    state: present
  when: focus_mode is defined

- name: CONFIGURE | Change mouse speed
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/mouse/speed"
    value: "{{ speed }}"
    state: present
  when: speed is defined

