---
- name: CONFIGURE | Show battery percentage
  community.general.dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "{{ show_battery_percentage }}"
    state: present
  when: show_battery_percentage is defined

