---
- name: CONFIGURE | Show battery percentage
  community.general.dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "{{ interface.show_battery_percentage | default(None) }}"
    state: "{{ 'present' if interface.show_battery_percentage is defined else 'absent' }}"

