---
- name: CONFIGURE | Prevent notifications showing on lock screen
  community.general.dconf:
    key: "/org/gnome/desktop/notifications/show-in-lock-screen"
    value: "{{ notifications.show_in_lock_screen | default(None) }}"
    state: "{{ 'present' if notifications.show_in_lock_screen is defined else 'absent' }}"

