---
- name: CONFIGURE | Set desktop background
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'{{ background.picture_uri | default(None) }}'"
    state: "{{ 'present' if background.picture_uri is defined else 'absent' }}"
